name: Build Snap.Net.Mobile

on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: true
        type: boolean
jobs:

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Install Xamarin toolchain
        run: |
          brew install mono
          brew install --cask xamarin-android
          brew install --cask xamarin-ios

      - name: Add Mono MSBuild
        run: echo "/Library/Frameworks/Mono.framework/Versions/Current/Commands" >> $GITHUB_PATH

      - name: Restore NuGet
        run: dotnet restore Snap.Net.sln
     
      - name: Build Android
        run: |
          xbuild Mobile/Mobile.Android/Snap.Net.Mobile.Android.csproj \
            /t:PackageForAndroid \
            /p:Configuration=Release

      - name: Build iOS
        run: |
          xbuild Mobile/Mobile.iOS/Snap.Net.Mobile.iOS.csproj \
            /p:Configuration=Release \
            /p:Platform=iPhoneSimulator \
            /t:Build

      - name: Upload Android APK
        if: inputs.upload_artifacts == true
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            **/*.apk

      - name: Upload iOS app
        if: inputs.upload_artifacts == true
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            **/*.app
