name: Build Snap.Net.Avalonia Windows

on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: true
        type: boolean
jobs:

  build-snapclient:
    runs-on: windows-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: vcpkg-${{ runner.os }}-x64-windows-release-v1

      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          pkgs: libflac libvorbis soxr opus boost-asio boost-beast
          triplet: x64-windows-release
          token: ${{ github.token }}

      - name: Build snapclient
        run: |
          cd SnapClient/snapcast
          mkdir build -Force
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release
          cmake --build . --config Release

      - name: Upload snapclient binary
        uses: actions/upload-artifact@v4
        with:
          name: snapclient-windows
          path: SnapClient/snapcast/bin/Release/


  build-windows:
    runs-on: windows-latest
    needs: build-snapclient

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.103'

      - name: Download snapclient
        uses: actions/download-artifact@v4
        with:
          name: snapclient-windows
          path: Snap.Net.Avalonia/snapclient/

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Publish Windows Package
        run: >
          dotnet publish Snap.Net.Avalonia/Snap.Net.Avalonia.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -p:Version=${{ vars.SNAP_VERSION }} -p:InformationalVersion=${{ vars.SNAP_VERSION }}

      - name: Upload Windows Artifact
        if: inputs.upload_artifacts == true
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: Snap.Net.Avalonia/bin/Release/net10.0/win-x64/publish/
